(function(){
const API='https://punjab-test-generator-ai-api.onrender.com',KEY='ptg_paper_studio_v3';
const TYPES=['MCQ','Short','Long','Numerical','CRQ','Practical','Translation','Grammar','Comprehension'];
const LABEL={MCQ:'MCQs',Short:'Short Q/A',Long:'Long Q/A',Numerical:'Numericals',CRQ:'CRQs',Practical:'Practical / Activities',Translation:'Translation',Grammar:'Grammar',Comprehension:'Comprehension'};
let tab='setup',remote=[],search='',type='All',difficulty='All',status='All',answerKey=false,version='A';
let S=load();
function defaults(){return{academy:'Your School / Academy',title:'Assessment Test',session:'2026-27',medium:'English',group:'General',testType:'School Test',pattern:'Custom',time:'60 Minutes',marks:50,instructions:'Attempt all required questions. Show complete working where applicable.',bookId:'',chapterId:'',selected:[],quotas:{MCQ:10,Short:5,Long:2,Numerical:0,CRQ:0,Practical:0,Translation:0,Grammar:0,Comprehension:0}}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaults()}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function E(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function qid(q){return q.id||('q-'+String(q.text||q.question||'').slice(0,70).replace(/\W+/g,'-'))}
function all(){
 let base=typeof allQuestions==='function'?allQuestions():[],teacher=[];
 try{teacher=JSON.parse(localStorage.getItem('ptg_teacher_bank_v2')||'[]')}catch{}
 const m=new Map();[...base,...teacher,...remote].forEach(q=>{if(q)m.set(qid(q),{...q,id:qid(q),text:q.text||q.question||''})});return [...m.values()]
}
function cls(){return(DATA.classes||[]).find(c=>Number(c.grade)===Number(selectedGrade))}
function bk(){const c=cls();return(c?.books||[]).find(b=>b.id===S.bookId)||selectedBook||c?.books?.[0]}
function ch(){return(bk()?.chapters||[]).find(c=>c.id===S.chapterId)}
function qt(q){const t=String(q.type||'Short').toLowerCase();return TYPES.find(x=>x.toLowerCase()===t)||(t.includes('mcq')?'MCQ':t.includes('long')?'Long':t.includes('numer')?'Numerical':t.includes('practical')?'Practical':'Short')}
function marks(q){return Number(q.marks)||({MCQ:1,Short:2,Long:5,Numerical:4,CRQ:4,Practical:3,Translation:3,Grammar:2,Comprehension:5}[qt(q)]||1)}
function picked(){const ids=new Set(S.selected);return all().filter(q=>ids.has(qid(q)))}
function groups(){const g={};TYPES.forEach(t=>g[t]=[]);picked().forEach(q=>g[qt(q)].push(q));return g}
function field(k,l,v,type='text'){return'<label>'+l+'<input id="a-'+k+'" class="paper-input" type="'+type+'" value="'+E(v)+'"></label>'}
function sel(k,l,opts,v){return'<label>'+l+'<select id="a-'+k+'" class="paper-input">'+opts.map(x=>'<option '+(x===v?'selected':'')+'>'+E(x)+'</option>').join('')+'</select></label>'}
function setup(){
 const c=cls(),b=bk(),chapters=b?.chapters||[],books=c?.books||[],g=groups(),need=TYPES.filter(t=>(S.quotas[t]||0)>g[t].length);
 return'<div class="adv-hero"><div><span class="adv-kicker">ADVANCED PAPER STUDIO</span><h2>Build a board-ready paper with exact controls.</h2><p>Class → book → chapter → type → blueprint → live A4 preview. Your paper setup and basket are saved locally.</p></div><div class="adv-hero-stat"><b>'+picked().length+'</b><span>selected</span></div></div>'+tabs()+
 '<div class="adv-grid"><section class="panel adv-main"><div class="adv-section-head"><div><span class="adv-kicker dark">PAPER SETUP</span><h3>Academic setup</h3></div><span class="adv-chip">'+E(S.pattern)+'</span></div>'+
 '<div class="adv-form-grid">'+field('academy','School / Academy',S.academy)+field('title','Test Title',S.title)+
 '<label>Class<select id="a-grade" class="paper-input">'+(DATA.classes||[]).map(x=>'<option value="'+x.grade+'" '+(Number(x.grade)===Number(selectedGrade)?'selected':'')+'>Class '+x.grade+'</option>').join('')+'</select></label>'+
 '<label>Book / Subject<select id="a-book" class="paper-input">'+books.map(x=>'<option value="'+E(x.id)+'" '+(x.id===b?.id?'selected':'')+'>'+E(x.title)+'</option>').join('')+'</select></label>'+
 '<label>Chapter scope<select id="a-chapter" class="paper-input"><option value="">Full selected book</option>'+chapters.map(x=>'<option value="'+E(x.id)+'" '+(x.id===S.chapterId?'selected':'')+'>'+E(x.title)+'</option>').join('')+'</select></label>'+
 field('session','Academic Session',S.session)+sel('medium','Medium',['English','Urdu','Bilingual'],S.medium)+sel('group','Group / Stream',['General','Science','Arts','Computer Science','Commerce'],S.group)+
 sel('testType','Test Type',['School Test','Monthly Test','Mid Term','Final Term','Board Practice','Academy Test','Custom'],S.testType)+sel('pattern','Pattern',['Custom','Board Style','Smart Syllabus','Chapter Test'],S.pattern)+field('time','Time',S.time)+field('marks','Total Marks',S.marks,'number')+'</div>'+
 '<label class="adv-full">Instructions<textarea id="a-instructions" class="manual-textarea" rows="3">'+E(S.instructions)+'</textarea></label>'+
 '<div class="adv-section-head"><div><span class="adv-kicker dark">QUESTION BLUEPRINT</span><h3>Separate categories</h3></div><button id="autoFill" class="paper-secondary">Auto-fill</button></div>'+
 '<div class="quota-grid">'+TYPES.map(t=>'<label><span>'+LABEL[t]+'</span><input class="paper-input quota" data-type="'+t+'" type="number" min="0" max="100" value="'+(S.quotas[t]||0)+'"></label>').join('')+'</div>'+
 '<div class="adv-blueprint-note"><b>Selected:</b> '+picked().length+' • <b>Basket marks:</b> '+picked().reduce((a,q)=>a+marks(q),0)+' • <b>Target marks:</b> '+Number(S.marks||0)+'</div>'+
 '<div class="adv-actions"><button id="openBank" class="primary">Open Question Bank</button><button id="openPreview" class="paper-secondary">Preview Paper</button><button id="clearBasket" class="paper-secondary">Clear Basket</button></div></section>'+
 '<aside class="panel adv-side"><span class="adv-kicker dark">PAPER HEALTH</span><h3>Live checks</h3>'+health(g,need,b,chapters)+'</aside></div>'
}
function tabs(){return'<div class="adv-tabs"><button class="'+(tab==='setup'?'on':'')+'" data-tab="setup">1. Blueprint</button><button class="'+(tab==='bank'?'on':'')+'" data-tab="bank">2. Question Bank</button><button class="'+(tab==='preview'?'on':'')+'" data-tab="preview">3. Preview</button></div>'}
function health(g,need,b,chapters){const total=Object.values(S.quotas).reduce((a,b)=>a+b,0),sel=picked().length;return'<div class="health-meter"><span style="width:'+Math.min(100,total?sel/total*100:0)+'%"></span></div>'+[['Questions',sel+'/'+total],['Marks',picked().reduce((a,q)=>a+marks(q),0)+'/'+S.marks],['Scope',ch()?.title||b?.title||'Not set'],['Missing',need.length?need.map(t=>LABEL[t]).join(', '):'None']].map(x=>'<div class="health-line"><span>'+E(x[0])+'</span><b>'+E(x[1])+'</b></div>').join('')+'<div class="health-note">'+(need.length?'Add questions for '+need.map(t=>LABEL[t]).join(', '):'All requested categories have enough selected records.')+'</div>'}
function bank(){
 const b=bk(),c=ch();let rows=all().filter(q=>{if(type!=='All'&&qt(q)!==type)return false;if(difficulty!=='All'&&String(q.difficulty||'').toLowerCase()!==difficulty)return false;if(status!=='All'&&!String(q.verificationStatus||q.status||'').toLowerCase().includes(status))return false;const hay=[q.text,q.question,q.topic,q.exercise,q.chapterTitle,q.bookTitle].join(' ').toLowerCase();return!search||hay.includes(search.toLowerCase())});
 if(b)rows=rows.filter(q=>!q.bookId||q.bookId===b.id||q.book===b.title);if(c)rows=rows.filter(q=>!q.chapterId||q.chapterId===c.id||q.chapter===c.title);
 const ids=new Set(S.selected);
 return tabs()+'<div class="panel"><div class="adv-section-head"><div><span class="adv-kicker dark">QUESTION BANK</span><h3>'+E(b?.title||'All subjects')+(c?' / '+E(c.title):'')+'</h3><p class="muted">'+rows.length+' matches • '+ids.size+' selected</p></div><div class="adv-actions compact"><button id="syncAI" class="paper-secondary">Sync AI Bank</button><button id="genAI" class="primary">Generate with Gemini</button><button id="manualQ" class="paper-secondary">+ Manual</button></div></div>'+
 '<div class="filter-row"><input id="bankSearch" class="search" placeholder="Search question, topic, exercise…" value="'+E(search)+'"><select id="bankType" class="select"><option>All</option>'+TYPES.map(t=>'<option '+(type===t?'selected':'')+'>'+t+'</option>').join('')+'</select><select id="bankDiff" class="select"><option>All</option>'+['easy','medium','hard'].map(x=>'<option '+(difficulty===x?'selected':'')+'>'+x+'</option>').join('')+'</select><select id="bankStatus" class="select"><option>All</option><option '+(status==='teacher'?'selected':'')+'>teacher</option><option '+(status==='ai'?'selected':'')+'>ai</option><option '+(status==='verified'?'selected':'')+'>verified</option></select></div>'+
 '<div class="bank-toolbar"><label><input id="selectVisible" type="checkbox"> Select visible</label><span>Scope is locked to the selected class/book/chapter.</span></div><div class="bank-list">'+(rows.slice(0,300).map(q=>card(q,ids.has(qid(q))).join('')||'<div class="builder-empty"><h3>No questions in this scope</h3><p>Generate with Gemini using licensed source material, or add a teacher question.</p></div>')+'</div></div>'
}
function card(q,on){const t=qt(q);return'<label class="bank-card '+(on?'picked':'')+'"><input class="bank-check" type="checkbox" data-qid="'+E(qid(q))+'" '+(on?'checked':'')+'><div class="bank-card-main"><div class="bank-meta"><b>'+LABEL[t]+'</b><span>'+marks(q)+' mark'+(marks(q)===1?'':'s')+'</span><span>'+E(q.difficulty||'standard')+'</span><span>'+E(q.verificationStatus||q.status||'practice')+'</span></div><div class="bank-q">'+E(q.text||q.question)+'</div><div class="bank-answer">Answer: '+E(q.answer||q.correctAnswer||'Review required')+'</div><div class="bank-source">Source: '+E(q.sourceRef||q.sourceType||'Mapped practice — teacher review required')+'</div></div></label>'}
function order(list){const shift='ABCD'.indexOf(version);return [...list].sort((a,b)=>{const aa=(qid(a).split('').reduce((n,c)=>n+c.charCodeAt(0),0)+shift*17)%997,bb=(qid(b).split('').reduce((n,c)=>n+c.charCodeAt(0),0)+shift*17)%997;return aa-bb})}
function preview(){
 const g=groups();TYPES.forEach(t=>g[t]=order(g[t]));const scope=bk(),qs=TYPES.flatMap(t=>g[t]);let n=1,body='';TYPES.forEach(t=>{if(!g[t].length)return;body+='<section class="paper-section"><div class="paper-section-head"><b>'+LABEL[t]+'</b><span>'+g[t].reduce((a,q)=>a+marks(q),0)+' marks</span></div><p class="paper-instruction">'+E(instruction(t))+'</p>'+g[t].map(q=>pq(q,n++)).join('')+'</section>'});
 const key=qs.map((q,i)=>'<div class="answer-row"><b>'+(i+1)+'.</b><span>'+E(q.answer||q.correctAnswer||'Review required')+'</span></div>').join('');
 return tabs()+'<div class="builder-topbar"><div><h2>Live A4 Preview</h2><p>Version '+version+' • '+qs.length+' questions • '+qs.reduce((a,q)=>a+marks(q),0)+' marks</p></div><div class="adv-actions compact"><select id="paperVersion" class="select">'+['A','B','C','D'].map(v=>'<option '+(v===version?'selected':'')+'>'+v+'</option>').join('')+'</select><button id="answerToggle" class="paper-secondary">'+(answerKey?'Hide':'Show')+' Answer Key</button><button id="printPaper" class="primary">Print / Save PDF</button></div></div><div class="paper-stage"><div class="paper-sheet"><div class="paper-brandline"></div><div class="paper-school">'+E(S.academy)+'</div><div class="paper-title">'+E(S.title)+'</div><div class="paper-subtitle">Punjab Curriculum Assessment</div><div class="paper-meta"><span><b>Class:</b> '+selectedGrade+'</span><span><b>Subject:</b> '+E(scope?.title||'')+'</span><span><b>Session:</b> '+E(S.session)+'</span><span><b>Time:</b> '+E(S.time)+'</span><span><b>Total Marks:</b> '+E(S.marks)+'</span></div><div class="paper-student"><span>Name: ____________________</span><span>Roll No: __________</span><span>Date: __________</span></div><p class="paper-instruction"><b>Instructions:</b> '+E(S.instructions)+'</p>'+(body||'<div class="paper-empty"><b>No questions selected.</b><span>Open Question Bank to add questions.</span></div>')+(answerKey?'<div class="answer-key"><h3>ANSWER KEY</h3>'+key+'</div>':'')+'</div></div>'
}
function instruction(t){return{MCQ:'Choose the correct option.',Short:'Answer briefly and precisely.',Long:'Answer in detail with relevant explanation.',Numerical:'Show formula, working and final answer.',CRQ:'Give a reasoned constructed response.',Practical:'Write procedure, observation and result.',Translation:'Translate accurately.',Grammar:'Apply the required language rule.',Comprehension:'Answer from the given passage.'}[t]}
function pq(q,i){let o=qt(q)==='MCQ'&&Array.isArray(q.options)?'<div class="paper-options">'+q.options.map((x,j)=>'<span>'+String.fromCharCode(65+j)+'. '+E(x)+'</span>').join('')+'</div>':'';return'<div class="paper-q"><div class="paper-q-text"><b>Q'+i+'.</b> '+E(q.text||q.question)+'</div><div class="paper-marks">['+marks(q)+']</div>'+o+'</div>'}
function render(){title.textContent='Advanced Paper Studio';app.innerHTML=tab==='setup'?setup():tab==='bank'?bank():preview();bind()}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});
 ['academy','title','session','medium','group','testType','pattern','time','marks','instructions'].forEach(k=>{const el=document.getElementById('a-'+k);if(el)el.oninput=()=>{S[k]=k==='marks'?Number(el.value)||0:el.value;save()}});
 const gr=document.getElementById('a-grade');if(gr)gr.onchange=()=>{selectedGrade=Number(gr.value);S.bookId='';S.chapterId='';S.selected=[];save();render()};
 const bo=document.getElementById('a-book');if(bo)bo.onchange=()=>{S.bookId=bo.value;S.chapterId='';S.selected=[];save();render()};
 const ca=document.getElementById('a-chapter');if(ca)ca.onchange=()=>{S.chapterId=ca.value;S.selected=[];save();render()};
 document.querySelectorAll('.quota').forEach(x=>x.oninput=()=>{S.quotas[x.dataset.type]=Number(x.value)||0;save()});
 const auto=document.getElementById('autoFill');if(auto)auto.onclick=()=>{const m=Number(S.marks)||50;S.quotas={MCQ:Math.round(m*.2),Short:Math.round(m*.2/2),Long:Math.round(m*.2/5),Numerical:0,CRQ:0,Practical:0,Translation:0,Grammar:0,Comprehension:0};save();render()};
 const ob=document.getElementById('openBank');if(ob)ob.onclick=()=>{tab='bank';render()};const op=document.getElementById('openPreview');if(op)op.onclick=()=>{tab='preview';render()};const cb=document.getElementById('clearBasket');if(cb)cb.onclick=()=>{S.selected=[];save();render()};
 const se=document.getElementById('bankSearch');if(se)se.oninput=e=>{search=e.target.value;render()};const bt=document.getElementById('bankType');if(bt)bt.onchange=e=>{type=e.target.value;render()};const bd=document.getElementById('bankDiff');if(bd)bd.onchange=e=>{difficulty=e.target.value;render()};const bs=document.getElementById('bankStatus');if(bs)bs.onchange=e=>{status=e.target.value;render()};
 document.querySelectorAll('.bank-check').forEach(x=>x.onchange=()=>{if(x.checked&&!S.selected.includes(x.dataset.qid))S.selected.push(x.dataset.qid);if(!x.checked)S.selected=S.selected.filter(id=>id!==x.dataset.qid);save();render()});
 const sv=document.getElementById('selectVisible');if(sv)sv.onchange=()=>{const ids=[...document.querySelectorAll('.bank-check')].map(x=>x.dataset.qid);S.selected=sv.checked?[...new Set([...S.selected,...ids])]:S.selected.filter(x=>!ids.includes(x));save();render()};
 const sync=document.getElementById('syncAI');if(sync)sync.onclick=syncAI;const gen=document.getElementById('genAI');if(gen)gen.onclick=gemini;const man=document.getElementById('manualQ');if(man)man.onclick=manual;
 const pv=document.getElementById('paperVersion');if(pv)pv.onchange=e=>{version=e.target.value;render()};const at=document.getElementById('answerToggle');if(at)at.onclick=()=>{answerKey=!answerKey;render()};const pp=document.getElementById('printPaper');if(pp)pp.onclick=()=>window.print()
}
async function syncAI(){const b=bk(),c=ch();if(!b){alert('Select a book first.');return}try{const u=new URL(API+'/questions');u.searchParams.set('grade',selectedGrade);u.searchParams.set('bookId',b.id);if(c)u.searchParams.set('chapterId',c.id);u.searchParams.set('limit','1000');const r=await fetch(u);remote=await r.json();tab='bank';render()}catch(e){alert('AI bank sync failed: '+e.message)}}
function gemini(){const b=bk(),c=ch();if(!b||!c){alert('Select an exact chapter before Gemini generation.');return}document.body.insertAdjacentHTML('beforeend','<div class="manual-modal-backdrop" id="gm"><div class="manual-modal"><div class="manual-modal-head"><div><span class="manual-kicker">GEMINI SOURCE-GROUNDED</span><h3>Generate for '+E(c.title)+'</h3><p>Paste licensed or teacher-provided source material for this exact chapter.</p></div><button id="gx" class="manual-x">×</button></div><div class="manual-form"><div class="manual-grid"><label>Type<select id="gt" class="paper-input">'+TYPES.map(t=>'<option>'+t+'</option>').join('')+'</select></label><label>Count<input id="gc" type="number" min="5" max="50" class="paper-input" value="10"></label></div><label>Source material<textarea id="gs" class="manual-textarea" rows="9" placeholder="Paste source text here…"></textarea></label><div class="manual-actions"><button id="gcx" class="paper-secondary">Cancel</button><button id="grun" class="primary">Generate + Add</button></div></div></div></div>');const close=()=>document.getElementById('gm')?.remove();document.getElementById('gx').onclick=close;document.getElementById('gcx').onclick=close;document.getElementById('grun').onclick=async()=>{const source=document.getElementById('gs').value.trim();if(source.length<100){alert('Provide enough source material for grounded generation.');return}const btn=document.getElementById('grun');btn.disabled=true;btn.textContent='Generating…';try{const r=await fetch(API+'/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({grade:Number(selectedGrade),bookId:b.id,bookTitle:b.title,chapterId:c.id,chapterTitle:c.title,topics:(c.topics||[]).map(x=>typeof x==='string'?x:x.title),sourceText:source,types:[document.getElementById('gt').value],count:Number(document.getElementById('gc').value)||10})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Generation failed');remote=[...remote,...(d.questions||[])];close();tab='bank';render();alert('Accepted '+(d.accepted||0)+' new questions.')}catch(e){alert(e.message);btn.disabled=false;btn.textContent='Generate + Add'}}}
function manual(){const b=bk(),c=ch();document.body.insertAdjacentHTML('beforeend','<div class="manual-modal-backdrop" id="tm"><div class="manual-modal"><div class="manual-modal-head"><div><span class="manual-kicker">TEACHER QUESTION</span><h3>Add Manual Question</h3></div><button id="tx" class="manual-x">×</button></div><div class="manual-form"><div class="manual-grid"><label>Type<select id="tt" class="paper-input">'+TYPES.map(t=>'<option>'+t+'</option>').join('')+'</select></label><label>Marks<input id="tk" type="number" min="1" max="20" class="paper-input" value="1"></label></div><label>Question<textarea id="tq" class="manual-textarea" rows="5"></textarea></label><label>Answer / Marking Guide<textarea id="ta" class="manual-textarea" rows="4"></textarea></label><div class="manual-actions"><button id="tc" class="paper-secondary">Cancel</button><button id="ts" class="primary">Save + Add</button></div></div></div></div>');const close=()=>document.getElementById('tm')?.remove();document.getElementById('tx').onclick=close;document.getElementById('tc').onclick=close;document.getElementById('ts').onclick=()=>{const q=document.getElementById('tq').value.trim(),a=document.getElementById('ta').value.trim();if(!q||!a){alert('Question and answer are required.');return}const x={id:'teacher-'+Date.now(),type:document.getElementById('tt').value,marks:Number(document.getElementById('tk').value)||1,text:q,answer:a,grade:Number(selectedGrade),bookId:b?.id||'',chapterId:c?.id||'',chapterTitle:c?.title||'',verificationStatus:'teacher-manual',sourceRef:'Teacher entered'};let arr=[];try{arr=JSON.parse(localStorage.getItem('ptg_teacher_bank_v2')||'[]')}catch{}arr.unshift(x);localStorage.setItem('ptg_teacher_bank_v2',JSON.stringify(arr));S.selected.push(x.id);save();close();tab='bank';render()}}
window.renderBuilder=render;
const nav=document.querySelector('.sidebar');if(nav&&!nav.querySelector('[data-view="advanced-bank"]')){const n=document.createElement('button');n.className='nav';n.dataset.view='advanced-bank';n.textContent='▣  Question Bank';const s=nav.querySelector('[data-view="sync"]');nav.insertBefore(n,s);n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');tab='bank';render()}}
const bnav=document.querySelector('[data-view="builder"]');if(bnav)bnav.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));bnav.classList.add('active');tab='setup';render()};
})();