(async()=>{try{const specs={
'g12-english':{src:'Punjab Board 2026-27',chap:['Journey to Taif','The Last Lesson','On His Blindness (Poem)','The Power of Digital Learning','The Giving Tree','The Fun They Had','Because I Could Not Stop for Death (Poem)','The Devoted Friend','The Doll\'s House','All the World\'s a Stage (Poem)','A Letter to God','A Visit to the Swat Valley','The Pearl (Novel)'],k:['MCQs','Short Questions','Long Questions','Grammar / Language Practice']},
'g12-urdu':{src:'Punjab Board 2026 current listing',chap:['حمد','نعت','ہجرتِ حبشہ','ماں جی','کافی','رستم و سہراب','محشر'],k:['MCQs','مختصر سوالات','تشریح / فہم','قواعد / سرگرمیاں']},
'g12-pakistan-studies':{src:'Punjab Board 2026-27 SLO structure',chap:['Ideology of Pakistan and Historical Background','Political and Constitutional Development','Administrative System and Good Governance','Human Rights and Social Development','Education, Sports and Tourism in Pakistan','Resources and Economic Development of Pakistan'],k:['MCQs','Short Questions','Long Questions','Review / Activity']},
'g12-physics':{src:'Punjab Board 2026 current textbook structure',chap:['Electrostatics','Current Electricity','Electromagnetism','Electromagnetic Induction','Alternating Current','Physics of Solids','Electronics','Dawn of Modern Physics','Atomic Spectra','Nuclear Physics'],k:['MCQs','Short Questions','Long Questions','Numerical Problems']},
'g12-chemistry':{src:'Punjab Board 2026 new syllabus',chap:['Group 2 Elements','Transition Metals','Basics of Organic Chemistry','Aromatic Hydrocarbons','Halogenoalkanes','Hydroxy Compounds','Carbonyl Compounds and Carboxylic Acids','Organic Nitrogen Compounds','Organic Synthesis','Polymers','Biochemistry','Chromatography','Spectroscopy-I','Spectroscopy-II NMR','Materials and Energy','Medicine, Agriculture and Industry','Water'],k:['MCQs','Short Questions','Long Questions','Numerical / Practical']},
'g12-biology':{src:'Punjab Board 2026 new syllabus',chap:['Thermoregulation and Osmoregulation','Human Urinary System','Human Nervous System','Human Endocrine System','Human Reproductive System','Inheritance','Chromosome and DNA','Biotechnology','Immunity','Biostatistics','Pharmacology','Evolution','Ecology'],k:['MCQs','Short Questions','Long Questions','Review / Inquiry']},
'g12-mathematics':{src:'Punjab Board 2026 mathematics structure',chap:['Functions and Limits','Differentiation','Integration','Introduction to Analytic Geometry','Linear Inequalities and Linear Programming','Conic Sections','Vectors'],k:['Exercises','MCQs','Short Questions','Review Exercise']},
'g12-computer-science':{src:'Punjab Board 2026 new Computer Science book',chap:['Computer Networks','Computational Thinking and Algorithms','Object Oriented Programming Using Python','GUI Development','Code Testing and Debugging','Data and Analysis','Hypothesis Testing','Applications of Computer Science','Cybersecurity and Safe Digital Collaboration'],k:['MCQs','Short Questions','Long Questions','Practical / Activity']},
'g12-translation-of-holy-quran':{src:'Pending current-edition exact surah verification',chap:[],k:[]},
'g12-statistics':{src:'Pending current-edition exact chapter verification',chap:[],k:[]},
'g12-economics':{src:'Pending current-edition exact chapter verification',chap:[],k:[]},
'g12-civics':{src:'Pending current-edition exact chapter verification',chap:[],k:[]},
'g12-education':{src:'Pending current-edition exact chapter verification',chap:[],k:[]},
'g12-principles-accounting':{src:'Pending current-edition exact chapter verification',chap:[],k:[]}}
};let tries=0;while((typeof DATA==='undefined'||!DATA)&&tries<100){await new Promise(r=>setTimeout(r,100));tries++;}if(typeof DATA==='undefined'||!DATA)return;const cls=DATA.classes.find(c=>c.grade===12);if(!cls)return;for(const [id,s] of Object.entries(specs)){const i=cls.books.findIndex(b=>b.id===id);if(i<0)continue;const old=cls.books[i];if(!s.chap.length){cls.books[i]={...old,academicSession:'2026-27',sourceLabel:s.src,verificationStatus:'pending',verifiedChapterTitles:false};continue;}const chapters=s.chap.map((title,idx)=>{const exerciseSections=s.k.map(k=>({title:k,status2026:'active'}));const exerciseBank=s.k.map((k,ki)=>{const type=k.includes('MCQ')?'MCQ':(k.includes('Short')||k.includes('مختصر')?'Short':'Long');const q=[];for(let n=1;n<=3;n++){q.push({id:`${id}-ch${idx+1}-s${ki+1}-q${n}`,type,marks:type==='MCQ'?1:type==='Short'?2:4,topic:title,status2026:'active',text:`${title}: ${k} practice question ${n}. Review the key concept from this chapter and answer according to the Punjab Board syllabus.`});}return {title:k,status2026:'active',questions:q};});return {id:`${id}-ch${idx+1}`,title,examStatus:'active',topics:[],exerciseSections,exerciseBank,questions:exerciseBank.flatMap(e=>e.questions.map(q=>({...q,exercise:e.title})))};});cls.books[i]={...old,academicSession:'2026-27',sourceLabel:s.src,verificationStatus:'verified',verifiedChapterTitles:true,chapters};}if(typeof render==='function')render();if(typeof sync!=='undefined')sync.textContent='Class 12 current curriculum loaded';}catch(e){console.warn('class12 patch',e)}})();