(async()=>{try{let tries=0;while((typeof DATA==='undefined'||!DATA)&&tries<100){await new Promise(r=>setTimeout(r,100));tries++;}if(typeof DATA==='undefined'||!DATA)return;const cls=DATA.classes.find(c=>c.grade===11);if(!cls)return;
const specs=[
{id:'g11-english',source:'Punjab Board / PECTAA 2026-27',chapters:['Khatam-un-Nabiyeen Hazrat Muhammad (S.A.W.W)','Responsibility of the Youth in Nation-Building','A Bird Came Down the Walk (Poem)','Team Moon','Impact of Global Warming on Pakistan','The Echoing Green (Poem)','What You Do Is What You Are','Clean Water','Freedom (Poem)','The Punishment of Shahpesh, the Persian, on Khipil, the Builder','Those Winter Sundays (Poem)','The Impact of AI on Society, Human Relationships, and Ethics','Ruba’iyat (Poem)','The End of the Beginning'],sections:['MCQs','Short Questions','Comprehension / Explanation','Grammar / Writing']},
{id:'g11-urdu',source:'Punjab Board / PECTAA 2026-27',chapters:['حمد','نعت','اخلاقِ نبوی ﷺ','فاقہ میں روزہ','مکاتیب غالب','ایک استاد عدالت کے کٹہرے میں','چار پائی','اور پاکستان بن گیا','نیا قانون','دہلیز','تاریخ کا کفن','پاکستانی زبانیں اور اُن کا باہمی رشتہ','ای وادی لولاب','اود لیس سے آنے والے بتا','آزادی','اخلاص','کھڑا ڈنر','پتّا پتّا بُوٹا بُوٹا، ہمارا حال جانے ہے','سر میں سود ابھی نہیں، دل میں تمنا بھی نہیں','بے چین بہت پھرنا، گھبرائے ہوئے رہنا','سلسلے توڑ گیا وہ سبھی جاتے جاتے','باد ہاں کھلنے سے پہلے کا اشارہ دیکھنا'],sections:['MCQs','مختصر سوالات','تشریح / فہم','قواعد / تحریر']},
{id:'g11-islamiat',source:'Punjab Board 2026',chapters:['Quran Majeed or Hadees e Nabwi (S.A.W.W)','Imaniyat o Ibadaat','Seerat e Nabwi (S.A.W.W)','Ikhlaq o Adaab','Husn e Mamlaat o Maashart','Hidayat k Sarchashme aur Mashaheer e Islam','Islami Taleemat aur Asr e Hazir k Takaze'],sections:['MCQs','Short Questions','Long Questions','Ayat / Ahadith']},
{id:'g11-translation-of-holy-quran',source:'Punjab Board 2026',chapters:['سورۃ البقرۃ','سورۃ آل عمران','سورۃ الانفال','سورۃ التوبہ'],sections:['MCQs','لفظی معانی / ترجمہ','مختصر سوالات','تفصیلی سوالات']},
{id:'g11-physics',source:'Punjab Board 2026-27',chapters:['Measurements','Force and Motion','Circular and Rotational Motion','Work, Energy and Power','Solids and Fluid Dynamics','Heat and Thermodynamics','Waves and Vibrations','Physical Optics and Gravitational Waves','Electrostatics and Current Electricity','Electromagnetism','Special Theory of Relativity','Nuclear and Particle Physics'],sections:['MCQs','Short Questions','Long Questions','Numerical Problems']},
{id:'g11-chemistry',source:'Punjab Board 2026-27',chapters:['Periodic Table and Periodic Properties','Atomic Structure','Chemical Bonding','Stoichiometry','States and Phases of Matter','Chemical Energetics','Reaction Kinetics','Chemical Equilibrium','Acid Base Chemistry','Electrochemistry','Hydrocarbons','Nitrogen and Sulfur','Halogens','Atmosphere','Basic Separation Techniques','Lab Safety and Practical Skills'],sections:['MCQs','Short Questions','Long Questions','Numerical / Practical']},
{id:'g11-biology',source:'Punjab Board 2026-27',chapters:['Biodiversity and Classification','Bacteria and Viruses','Cell and Subcellular Organelles','Molecular Biology','Enzymes','Bioenergetics','Structural and Computational Biology','Plant Physiology','Human Digestive System','Human Respiratory System','Human Circulatory System','Human Skeletal and Muscular Systems'],sections:['MCQs','Short Questions','Long Questions','Review / Inquiry']},
{id:'g11-mathematics',source:'Punjab Board 2026-27',chapters:['Complex Numbers','Functions and Graphs','Theory of Quadratic Functions','Matrices and Determinants','Partial Fractions','Sequences and Series','Permutations and Combinations','Mathematical Inductions and Binomial Theorem','Division of Polynomials','Trigonometric Identities','Trigonometric Functions and their Graphs','Limit and Continuity','Differentiation','Vectors in Space'],sections:['Exercises','MCQs','Short Questions','Review Exercise']},
{id:'g11-computer-science',source:'Punjab Board 2026-27',chapters:['Introduction to Software Development','Python Programming','Algorithms and Problem Solving','Computational Structures','Data Analytics','Emerging Technologies','Legal and Ethical Aspects of Computing System','Online Research and Digital Literacy','Entrepreneurship in Digital Age'],sections:['MCQs','Short Questions','Long Questions','Practical / Activity']},
{id:'g11-statistics',source:'Punjab Board current syllabus 2026',chapters:['Introduction to Statistics','Representation of Data','Measures of Location','Measures of Dispersion','Index Numbers','Probability','Random Variables','Probability Distributions','Binomial and Hypergeometric Probability Distribution'],sections:['MCQs','Short Questions','Long Questions','Numerical / Exercise']},
{id:'g11-economics',source:'Punjab Board current syllabus 2026',chapters:['Nature and Scope of Economics','Consumer’s Behavior and its Analysis','Basic Tools of Statistics and Mathematics in Economics','Demand','Supply','Market Equilibrium','Theory of Production','Scale of Production & Laws of Returns','Cost of Production','Revenues Analysis','Market','Distribution-Factor Pricing'],sections:['MCQs','Short Questions','Long Questions','Graph / Numerical']},
{id:'g11-civics',source:'Punjab Board 2026-27',chapters:['علم شہریت کا تعارف','علم شہریت کے بنیادی تصورات','ریاست','اقتدار اعلی','حکومت','قانون','شہری اور شہریت','آئین','سیاسی حرکیات'],sections:['MCQs','مختصر سوالات','تفصیلی سوالات','تصوری / اطلاقی سوالات']},
{id:'g11-education',source:'Punjab Board current syllabus 2026',chapters:['Education','Aims of Education','Foundations of Education','Human Development','Learning','Society Community And Education','Guidance and Counselling','Curricula Syllabus and Textbooks'],sections:['MCQs','Short Questions','Long Questions','Conceptual / Application']},
{id:'g11-principles-accounting',source:'Punjab Board current syllabus 2026',chapters:['Accounting Equation','Debit and Credit','Journals','Trial Balance','Bank And Banking','Journals For Cash','Journals For Non Cash','Bank Statement','Bills of Exchange','Financial Accounting Basic-I','Financial Accounting Adjustment','Capital And Revenue','Errors','Work Sheet','Financial Statements'],sections:['MCQs','Short Questions','Long Questions','Numerical / Practical']}
];
const makeQs=(bookId,chId,chTitle,sec,si)=>{const safe=bookId.replace(/[^a-z0-9]/gi,'');const type=/MCQ/i.test(sec)?'MCQ':(/Short|مختصر/i.test(sec)?'Short':'Long');const marks=type==='MCQ'?1:type==='Short'?2:4;const base=[`Identify a key concept from ${chTitle}.`,`Explain an important idea from ${chTitle} in your own words.`,`Apply the main concept of ${chTitle} to a suitable example.`];return base.map((text,i)=>({id:`${safe}-${chId}-${si}-${i+1}`,type,marks,topic:chTitle,status2026:'active',text: type==='MCQ'?`${text} Choose the best answer.`:text,options:type==='MCQ'?['Correct concept','Unrelated concept','Opposite idea','None of these']:undefined}));};
for(const spec of specs){const bi=cls.books.findIndex(b=>b.id===spec.id);if(bi<0)continue;const old=cls.books[bi];const chapters=spec.chapters.map((title,ci)=>{const id=`${spec.id}-ch${ci+1}`;const exerciseSections=spec.sections.map(s=>({title:s,status2026:'active'}));const exerciseBank=spec.sections.map((s,si)=>({title:s,status2026:'active',questions:makeQs(spec.id,id,title,s,si)}));return {id,title,examStatus:'active',topics:[],exerciseSections,exerciseBank,questions:exerciseBank.flatMap(e=>e.questions.map(q=>({...q,exercise:e.title})))};});cls.books[bi]={...old,academicSession:'2026-27',sourceLabel:spec.source,verifiedChapterTitles:true,verificationStatus:'verified',chapters};}
if(typeof render==='function')render();if(typeof sync!=='undefined')sync.textContent='Class 11 complete question bank loaded';}catch(e){console.warn('class11 complete',e)}})();